import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './globals.css';
import '@webcomponents/i2cwebcomponents/dist/themes/light.css';
import DSMSetup from "./DSMSetup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div i2c-container="container lg" className="containerBox">
      <DSMSetup>
            {children}
     </DSMSetup>
     </div>
    </body>
    </html>
  );
}
